import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function AuthLayout({ children }) {
    return (
      <div className="bg-black w-full">
            <div className="p-[2rem] absolute">
              <Link href={"/"} >
            HOME

              </Link>

            </div>
            {children}
      </div>
    );
  }
  