"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider.jsx";
import NavBar from "@/components/Navbar.jsx";
import Footer from "@/components/Footer";
import { usePathname } from "next/navigation";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "./reduxProvider";
import { useSelector } from "react-redux";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  
  let pathName = usePathname()

  if (pathName.includes("/auth")) {
    pathName = true
  } else {
    pathName = false
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Providers>
            {!pathName && <NavBar />}
            {children}
            {/* {!pathName && <Footer />} */}
            <Toaster position="bottom-right"
              toastOptions={{
                className: '',
                style: {
                  background: "black",
                  border: '1px solid gray',
                  padding: '16px',
                  color: 'white',
                },
              }}
            />
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
