"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider.jsx";
import NavBar from "@/components/Navbar.jsx";
import Footer from "@/components/Footer";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  let pathName = usePathname()
  
  if (pathName.includes("/auth")) {
    pathName = true
  } else {
    pathName = false
  }
  
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          {!pathName && <NavBar />}

          {children}
          {!pathName && <Footer />}
        </Providers>
      </body>
    </html>
  );
}
